### ISSUE TITLE
Официальный репозиторий

### ISSUE THREAD

**Issue by peter-gribanov** [fias-api/jquery#3]
Поясните пожалуйста какой из проектов является основным. Этот или [jquery.kladr](https://github.com/garakh/kladrapi-jsclient)? Судя по активности второй, хотя ссылки указывают на этот.

Вы имеете отношение к разработчикам самого [КЛАДР API](http://kladr-api.ru/) и это официальный клиент для API или это пользовательская разработка?

**Comment by garakh** [comment]
Мы являемся разработчиками КЛАДР в облаке. Так как формат КЛАДР устарел и все переходят на ФИАС мы так же решили переименовать проект в ФИАС в облаке и постепенно перейдем и на другой домен в том числе (fias-api.ru). Поэтому мы выпустили обновленный плагин для jquery. 

Таким образом, данный плагин является последним активным. В описании же https://github.com/garakh/kladrapi-jsclient сказано, что плагин устарел.

**Comment by peter-gribanov** [comment]
@garakh спасибо за разъяснение :+1:
