### ISSUE TITLE
Выбор города

### ISSUE THREAD

**Issue by kossmokvin** [fias-api/jquery#4]
```
jQuery('input').fias({
    type: 'city',
});
```
Выбор города в том виде, в котором сейчас есть - абсолютно бесполезен.
Название городов повторяются и непонятно из какого региона каждый город. В объекте о городе нет информации о регионе.

Попытка получить регион вместе с городом ( `type: ['region', 'city',]` ) приводит к ошибке типа (хотя в документации написано "перечисление типов", а не "тип" ).

Попытка не ограничивать тип, а затем доставать из объекта только регион и город - приводит к тому, что получаю на выходе список из одного и того же города, который выдаёт разные адреса, но город получается тот же....

------
Вероятно, придётся делать в два поля, с предварительным выбором региона, чтобы добиться адекватного поведения. Но очень жаль, что это не решилось стандартным образом - наличием информации о регионе в объекте города, для соответствующего последующего вывода через настройку лейбла.

**Comment by garakh** [comment]
Посмотрите на пример https://github.com/fias-api/jquery/blob/master/examples/form/script.js
Для вывода информации о родителях добавьте 

```
jQuery('input').fias({
    type: 'city',
    withParents: true
});
```

**Comment by kossmokvin** [comment]
Спасибо! Не заметил... 
Закрываю
