### ISSUE TITLE
Неправильный путь в примерах

### ISSUE THREAD

**Issue by tadapp** [fias-api/jquery#8]
Во всех примерах используется путь к файлу jquery.kladr.min
на самом деле нужно использовать путь до файла jquery.fias.min
первого не существует.

**Comment by garakh** [comment]
Да, спасибо, такая проблем есть, исправим в течение пары дней.

**Comment by belyakovav** [comment]
Так и не исправили. И в примерах не отрабатывает скрипт : script.js:3 Uncaught TypeError: $(...).kladr is not a function
    at HTMLDocument.<anonymous> (script.js:3)
    at j (jquery-1.11.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js:2)
    at Function.ready (jquery-1.11.1.min.js:2)
    at HTMLDocument.J (jquery-1.11.1.min.js:2)
(anonymous) @ script.js:3
j @ jquery-1.11.1.min.js:2
fireWith @ jquery-1.11.1.min.js:2
ready @ jquery-1.11.1.min.js:2
J @ jquery-1.11.1.min.js:2

**Comment by belyakovav** [comment]
И в скриптах к примерам необходимо изменить  с kladr на fias тогда заработает
